[package]
name = "fun"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.35", features = ["derive"] }
device_query = "3.0.1"
eyre = "0.6.12"
jiff = "0.2.5"
log = "0.4.27"
tokio = { version = "1.44.1", features = ["full"] }

[dev-dependencies]
enigo = "0.3.0"
