use serde::{Deserialize, Deserializer, Serialize};

#[derive(Debug, Serialize, Deserialize, Copy, Clone, Eq, PartialEq, Hash)]
pub enum Keycode {
    Key0,
    Key1,
    Key2,
    Key3,
    Key4,
    Key5,
    Key6,
    Key7,
    Key8,
    Key9,
    A,
    B,
    C,
    D,
    E,
    F,
    G,
    H,
    I,
    J,
    K,
    L,
    M,
    N,
    O,
    P,
    Q,
    R,
    S,
    T,
    U,
    V,
    W,
    X,
    Y,
    Z,
    F1,
    F2,
    F3,
    F4,
    F5,
    F6,
    F7,
    F8,
    F9,
    F10,
    F11,
    F12,
    F13,
    F14,
    F15,
    F16,
    F17,
    F18,
    F19,
    F20,
    Escape,
    Space,
    LControl,
    RControl,
    LShift,
    RShift,
    LAlt,
    RAlt,
    // TODO rename `Command` into `RCommand` at new major release
    Command,
    RCommand,
    LOption,
    ROption,
    LMeta,
    RMeta,
    Enter,
    Up,
    Down,
    Left,
    Right,
    Backspace,
    CapsLock,
    Tab,
    Home,
    End,
    PageUp,
    PageDown,
    Insert,
    Delete,

    // Numpad keys which have not been implemented: NumpadSeparator NumLock
    Numpad0,
    Numpad1,
    Numpad2,
    Numpad3,
    Numpad4,
    Numpad5,
    Numpad6,
    Numpad7,
    Numpad8,
    Numpad9,
    NumpadSubtract,
    NumpadAdd,
    NumpadDivide,
    NumpadMultiply,
    NumpadEquals,
    NumpadEnter,
    NumpadDecimal,

    // The following keys names represent the position of the key in a US keyboard,
    // not the sign value. In a different keyboards and OS, the position can vary.
    Grave,
    Minus,
    Equal,
    LeftBracket,
    RightBracket,
    BackSlash,
    Semicolon,
    Apostrophe,
    Comma,
    Dot,
    Slash,
}
impl Keycode {
    pub fn new(value: device_query::Keycode) -> Self {
        match value {
            device_query::Keycode::Key0 => Keycode::Key0,
            device_query::Keycode::Key1 => Keycode::Key1,
            device_query::Keycode::Key2 => Keycode::Key2,
            device_query::Keycode::Key3 => Keycode::Key3,
            device_query::Keycode::Key4 => Keycode::Key4,
            device_query::Keycode::Key5 => Keycode::Key5,
            device_query::Keycode::Key6 => Keycode::Key6,
            device_query::Keycode::Key7 => Keycode::Key7,
            device_query::Keycode::Key8 => Keycode::Key8,
            device_query::Keycode::Key9 => Keycode::Key9,
            device_query::Keycode::A => Keycode::A,
            device_query::Keycode::B => Keycode::B,
            device_query::Keycode::C => Keycode::C,
            device_query::Keycode::D => Keycode::D,
            device_query::Keycode::E => Keycode::E,
            device_query::Keycode::F => Keycode::F,
            device_query::Keycode::G => Keycode::G,
            device_query::Keycode::H => Keycode::H,
            device_query::Keycode::I => Keycode::I,
            device_query::Keycode::J => Keycode::J,
            device_query::Keycode::K => Keycode::K,
            device_query::Keycode::L => Keycode::L,
            device_query::Keycode::M => Keycode::M,
            device_query::Keycode::N => Keycode::N,
            device_query::Keycode::O => Keycode::O,
            device_query::Keycode::P => Keycode::P,
            device_query::Keycode::Q => Keycode::Q,
            device_query::Keycode::R => Keycode::R,
            device_query::Keycode::S => Keycode::S,
            device_query::Keycode::T => Keycode::T,
            device_query::Keycode::U => Keycode::U,
            device_query::Keycode::V => Keycode::V,
            device_query::Keycode::W => Keycode::W,
            device_query::Keycode::X => Keycode::X,
            device_query::Keycode::Y => Keycode::Y,
            device_query::Keycode::Z => Keycode::Z,
            device_query::Keycode::F1 => Keycode::F1,
            device_query::Keycode::F2 => Keycode::F2,
            device_query::Keycode::F3 => Keycode::F3,
            device_query::Keycode::F4 => Keycode::F4,
            device_query::Keycode::F5 => Keycode::F5,
            device_query::Keycode::F6 => Keycode::F6,
            device_query::Keycode::F7 => Keycode::F7,
            device_query::Keycode::F8 => Keycode::F8,
            device_query::Keycode::F9 => Keycode::F9,
            device_query::Keycode::F10 => Keycode::F10,
            device_query::Keycode::F11 => Keycode::F11,
            device_query::Keycode::F12 => Keycode::F12,
            device_query::Keycode::F13 => Keycode::F13,
            device_query::Keycode::F14 => Keycode::F14,
            device_query::Keycode::F15 => Keycode::F15,
            device_query::Keycode::F16 => Keycode::F16,
            device_query::Keycode::F17 => Keycode::F17,
            device_query::Keycode::F18 => Keycode::F18,
            device_query::Keycode::F19 => Keycode::F19,
            device_query::Keycode::F20 => Keycode::F20,
            device_query::Keycode::Escape => Keycode::Escape,
            device_query::Keycode::Space => Keycode::Space,
            device_query::Keycode::LControl => Keycode::LControl,
            device_query::Keycode::RControl => Keycode::RControl,
            device_query::Keycode::LShift => Keycode::LShift,
            device_query::Keycode::RShift => Keycode::RShift,
            device_query::Keycode::LAlt => Keycode::LAlt,
            device_query::Keycode::RAlt => Keycode::RAlt,
            device_query::Keycode::Command => Keycode::Command,
            device_query::Keycode::RCommand => Keycode::RCommand,
            device_query::Keycode::LOption => Keycode::LOption,
            device_query::Keycode::ROption => Keycode::ROption,
            device_query::Keycode::LMeta => Keycode::LMeta,
            device_query::Keycode::RMeta => Keycode::RMeta,
            device_query::Keycode::Enter => Keycode::Enter,
            device_query::Keycode::Up => Keycode::Up,
            device_query::Keycode::Down => Keycode::Down,
            device_query::Keycode::Left => Keycode::Left,
            device_query::Keycode::Right => Keycode::Right,
            device_query::Keycode::Backspace => Keycode::Backspace,
            device_query::Keycode::CapsLock => Keycode::CapsLock,
            device_query::Keycode::Tab => Keycode::Tab,
            device_query::Keycode::Home => Keycode::Home,
            device_query::Keycode::End => Keycode::End,
            device_query::Keycode::PageUp => Keycode::PageUp,
            device_query::Keycode::PageDown => Keycode::PageDown,
            device_query::Keycode::Insert => Keycode::Insert,
            device_query::Keycode::Delete => Keycode::Delete,
            device_query::Keycode::Numpad0 => Keycode::Numpad0,
            device_query::Keycode::Numpad1 => Keycode::Numpad1,
            device_query::Keycode::Numpad2 => Keycode::Numpad2,
            device_query::Keycode::Numpad3 => Keycode::Numpad3,
            device_query::Keycode::Numpad4 => Keycode::Numpad4,
            device_query::Keycode::Numpad5 => Keycode::Numpad5,
            device_query::Keycode::Numpad6 => Keycode::Numpad6,
            device_query::Keycode::Numpad7 => Keycode::Numpad7,
            device_query::Keycode::Numpad8 => Keycode::Numpad8,
            device_query::Keycode::Numpad9 => Keycode::Numpad9,
            device_query::Keycode::NumpadSubtract => Keycode::NumpadSubtract,
            device_query::Keycode::NumpadAdd => Keycode::NumpadAdd,
            device_query::Keycode::NumpadDivide => Keycode::NumpadDivide,
            device_query::Keycode::NumpadMultiply => Keycode::NumpadMultiply,
            device_query::Keycode::NumpadEquals => Keycode::NumpadEquals,
            device_query::Keycode::NumpadEnter => Keycode::NumpadEnter,
            device_query::Keycode::NumpadDecimal => Keycode::NumpadDecimal,
            device_query::Keycode::Grave => Keycode::Grave,
            device_query::Keycode::Minus => Keycode::Minus,
            device_query::Keycode::Equal => Keycode::Equal,
            device_query::Keycode::LeftBracket => Keycode::LeftBracket,
            device_query::Keycode::RightBracket => Keycode::RightBracket,
            device_query::Keycode::BackSlash => Keycode::BackSlash,
            device_query::Keycode::Semicolon => Keycode::Semicolon,
            device_query::Keycode::Apostrophe => Keycode::Apostrophe,
            device_query::Keycode::Comma => Keycode::Comma,
            device_query::Keycode::Dot => Keycode::Dot,
            device_query::Keycode::Slash => Keycode::Slash,
        }
    }
}
